name: Build Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Download Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Publish Test Results
        uses: dorny/test-reporter@v1.6.0
        if: always()
        with:
          name: Tests Results
          path: reports/test-results.xml
          reporter: java-junit

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        with:
          args: >
            -Dsonar.organization=cbrather
            -Dsonar.projectKey=CBrather_carman-webapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: npm run build
